# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Database
    before: |
     echo 'Configuring Database...'
     pg_stop 
     pg_start 
    init: pg_isready 
    command: psql -h localhost -d postgres -f ddl.sql
  - name: SpringBoot
    init: ./mvnw clean install
    command: ./mvnw spring-boot:run
image: gitpod/workspace-postgres

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
