ports:
  - port: 8080
tasks:
  - name: Database 
    before: echo 'Creating tables...'
    init: postgres < ddl.sql
    command: psql -h localhost -d postgres -f ddl.sql
  - name: SprinBoot
    before: echo 'Initializing Spring Boot on 8080'
    init: ./mvnw clean install
    command: ./mvnw spring-boot:run
image: gitpod/workspace-postgres